export default {
  Buttons: {
    viewControlsButton : 'viewControlsButton',
    freeHandToolButton : 'freeHandToolButton',
    highlightToolButton : 'highlightToolButton',
    underlineToolButton : 'underlineToolButton',
    squigglyToolButton : 'squigglyToolButton',
    strikeoutToolButton : 'strikeoutToolButton',
    rectangleToolButton : 'rectangleToolButton',
    ellipseToolButton : 'ellipseToolButton',
    lineToolButton : 'lineToolButton',
    arrowToolButton : 'arrowToolButton',
    polylineToolButton : 'polylineToolButton',
    polygonToolButton : 'polygonToolButton',
    cloudToolButton : 'cloudToolButton',
    signatureToolButton : 'signatureToolButton',
    freeTextToolButton : 'freeTextToolButton',
    stickyToolButton : 'stickyToolButton',
    calloutToolButton : 'calloutToolButton',
    stampToolButton : 'stampToolButton',
    toolsButton : 'toolsButton',
    searchButton : 'searchButton',
    shareButton : 'shareButton',
    thumbnailsButton : 'thumbnailsButton',
    listsButton : 'listsButton',
    thumbnailSlider : 'thumbnailSlider',
  },
  Tools: {
    annotationEdit : 'AnnotationEdit',
    textSelect : 'TextSelect',
    annotationCreateSticky : 'AnnotationCreateSticky',
    annotationCreateFreeHand : 'AnnotationCreateFreeHand',
    annotationCreateTextHighlight : 'AnnotationCreateTextHighlight',
    annotationCreateTextUnderline : 'AnnotationCreateTextUnderline',
    annotationCreateTextSquiggly : 'AnnotationCreateTextSquiggly',
    annotationCreateTextStrikeout : 'AnnotationCreateTextStrikeout',
    annotationCreateFreeText : 'AnnotationCreateFreeText',
    annotationCreateCallout : 'AnnotationCreateCallout',
    annotationCreateSignature : 'AnnotationCreateSignature',
    annotationCreateLine : 'AnnotationCreateLine',
    annotationCreateArrow : 'AnnotationCreateArrow',
    annotationCreatePolyline : 'AnnotationCreatePolyline',
    annotationCreateStamp : 'AnnotationCreateStamp',
    annotationCreateRectangle : 'AnnotationCreateRectangle',
    annotationCreateEllipse : 'AnnotationCreateEllipse',
    annotationCreatePolygon : 'AnnotationCreatePolygon',
    annotationCreatePolygonCloud : 'AnnotationCreatePolygonCloud',
    annotationCreateDistanceMeasurement : 'AnnotationCreateDistanceMeasurement',
    annotationCreatePerimeterMeasurement : 'AnnotationCreatePerimeterMeasurement',
    annotationCreateAreaMeasurement : 'AnnotationCreateAreaMeasurement',
  }
};