export default {
  Buttons: {
    viewControlsButton : 'viewControlsButton',
    freeHandToolButton : 'freeHandToolButton',
    highlightToolButton : 'highlightToolButton',
    underlineToolButton : 'underlineToolButton',
    squigglyToolButton : 'squigglyToolButton',
    strikeoutToolButton : 'strikeoutToolButton',
    rectangleToolButton : 'rectangleToolButton',
    ellipseToolButton : 'ellipseToolButton',
    lineToolButton : 'lineToolButton',
    arrowToolButton : 'arrowToolButton',
    polylineToolButton : 'polylineToolButton',
    polygonToolButton : 'polygonToolButton',
    cloudToolButton : 'cloudToolButton',
    signatureToolButton : 'signatureToolButton',
    freeTextToolButton : 'freeTextToolButton',
    stickyToolButton : 'stickyToolButton',
    calloutToolButton : 'calloutToolButton',
    stampToolButton : 'stampToolButton',
    toolsButton : 'toolsButton',
    searchButton : 'searchButton',
    shareButton : 'shareButton',
    editPagesButton: 'editPagesButton',
    printButton: 'printButton',
    closeButton: 'closeButton',
    saveCopyButton: 'saveCopyButton',
    formToolsButton: 'formToolsButton',
    moreItemsButton: 'moreItemsButton',
    thumbnailsButton : 'thumbnailsButton',
    listsButton : 'listsButton',
    thumbnailSlider : 'thumbnailSlider',
    outlineListButton: 'outlineListButton',
    annotationListButton: 'annotationListButton',
    userBookmarkListButton: 'userBookmarkListButton',
  },
  Tools: {
    annotationEdit : 'AnnotationEdit',
    textSelect : 'TextSelect',
    annotationCreateSticky : 'AnnotationCreateSticky',
    annotationCreateFreeHand : 'AnnotationCreateFreeHand',
    annotationCreateTextHighlight : 'AnnotationCreateTextHighlight',
    annotationCreateTextUnderline : 'AnnotationCreateTextUnderline',
    annotationCreateTextSquiggly : 'AnnotationCreateTextSquiggly',
    annotationCreateTextStrikeout : 'AnnotationCreateTextStrikeout',
    annotationCreateFreeText : 'AnnotationCreateFreeText',
    annotationCreateCallout : 'AnnotationCreateCallout',
    annotationCreateSignature : 'AnnotationCreateSignature',
    annotationCreateLine : 'AnnotationCreateLine',
    annotationCreateArrow : 'AnnotationCreateArrow',
    annotationCreatePolyline : 'AnnotationCreatePolyline',
    annotationCreateStamp : 'AnnotationCreateStamp',
    annotationCreateRectangle : 'AnnotationCreateRectangle',
    annotationCreateEllipse : 'AnnotationCreateEllipse',
    annotationCreatePolygon : 'AnnotationCreatePolygon',
    annotationCreatePolygonCloud : 'AnnotationCreatePolygonCloud',
    annotationCreateDistanceMeasurement : 'AnnotationCreateDistanceMeasurement',
    annotationCreatePerimeterMeasurement : 'AnnotationCreatePerimeterMeasurement',
    annotationCreateAreaMeasurement : 'AnnotationCreateAreaMeasurement',
  },
  FitMode: {
    FitPage: 'FitPage',
    FitWidth: 'FitWidth',
    FitHeight: 'FitHeight',
    Zoom: 'Zoom',
  },
  LayoutMode: {
    Single: 'Single',
    Continuous: 'Continuous',
    Facing: 'Facing',
    FacingContinuous: 'FacingContinuous',
    FacingCover: 'FacingCover',
    FacingCoverContinuous: 'FacingCoverContinuous',
  }
};