name: Update Package Version
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo.
          ref: ${{ github.event.pull_request.head.sha }} # checks out the branch being merged into `master`
      
      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run:  npm install json   

      - run: git fetch 
      - run: git checkout -m orgin/master package.json 
      - run: git add package.json
      - run: git commit  

      - name: Update package.json
        run: bash ./scripts/update_version.sh

      - name: Add package.json 
        run: git add package.json  

      - name: Commit files
        run: | # Change last line to your preferred commit message (I like `chore: build js files`).
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Updating JS files" -a || echo "No commit needed. JS files are already up-to-date"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }} # pushes the commit to the branch being merged into `master`